### ISSUE TITLE
brew update warning

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/homebrew-eosio#50]
I'm getting the following error from brew:

```
% brew upgrade
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the eosio/eosio tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio/eosio.rb:19
```

**Comment by gleehokie** [comment]
`brew style --fix eosio` will resolve this warning.  @kj4ezj you should also resolve the rest of the issues listed by `brew style` when you get a chance.

**Comment by kj4ezj** [comment]
Thank you for reporting this! I have opened story [EPE-944](https://blockone.atlassian.net/browse/EPE-944) to get this prioritized.

**Comment by kj4ezj** [comment]
@wly99 also opened [issue 54](https://github.com/EOSIO/homebrew-eosio/issues/54) with the same issue:  
  
> Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.

> Hello! I faced this issue while trying to install EOS. Original warning was:
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the eosio/eosio tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio/eosio.rb:19

> Read the other issue and ran "brew style --fix eosio" but still ended up with that warning at the top.

**Comment by kj4ezj** [comment]
@killshot13 put forward [pull request 52](https://github.com/EOSIO/homebrew-eosio/pull/52) with a proposed fix. We can integrate Michael's code into the macOS package generation script, [/scripts/generate_bottle.sh](https://github.com/EOSIO/eos/blob/develop/scripts/generate_bottle.sh), in [eos](https://github.com/EOSIO/eos) on all the supported branches.

**Comment by kj4ezj** [comment]
Tested working on Catalina.
<img width="1221" alt="Screen Shot 2021-06-22 at 3 59 05 PM" src="https://user-images.githubusercontent.com/34947245/122991338-e8c6b080-d372-11eb-9eea-f6c2b1d80ac2.png">
